
services:
  porking:
    build:
      context: .
    container_name: "porking"
    ports:
      - "1234:1234"

  porking-database:
    image: "postgres:alpine"
    container_name: "porking-db"
    restart: always
    environment:
      POSTGRES_PASSWORD: blessium
      POSTGRES_USER: blessium

  porking-kafka:
    image: "docker.io/bitnami/kafka:3.4"
    container_name: "porking-kafka"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"


