
services:
  porking:
    build:
      context: .
    container_name: "porking"
    ports:
      - "1234:1234"

  porking-database:
    image: "postgres:alpine"
    container_name: "porking-db"
    restart: always
    environment:
      POSTGRES_PASSWORD: blessium
      POSTGRES_USER: blessium
